source 'https://github.com/CocoaPods/Specs.git'

target 'RamblerSegues_Example', :exclusive => true do
  pod "RamblerSegues", :path => "../"
end

target 'RamblerSegues_Tests', :exclusive => true do
  pod "RamblerSegues", :path => "../"

  
end
